### PR TITLE
Implement the fill iterator

### PR DESCRIPTION
**Pull request by jsternberg**
Fill requires an additional function for IteratorCreator to retrieve the
series that will be returned from the iterator. When fill is required
for an aggregate, the IteratorCreator will be asked what series will be
returned by the created iterator.

### CODE REVIEW

**Comment by jsternberg** [comment]
Almost done implementing the fill iterator. The last thing I'm stuck on is what to do when an appropriate time interval isn't given. For example, you can run this query and cause the server to get stuck:

```
SELECT mean(value) FROM cpu WHERE time > now() - 5m GROUP BY time(1m)
```

Right now, this will cause it to compute an interval from 5 minutes in the past until sometime in 2050 because the end time wasn't set. Not sure the correct way to tackle this at the moment other than try to modify the parser to reject this kind of time interval.

**Comment by jsternberg** [comment]
There is also still a question about how fill should act when it comes to tags and missing intervals. So if you have a shard with a measurement (`cpu`) and it has two tags (`host=A` and `host=B`), what do you do when there are no points for `host=B` in the interval with the following query?

```
SELECT mean(value) FROM cpu WHERE time >= now() - 30s AND time < now() GROUP BY time(10s), host

cpu,host=A value=1 0
cpu,host=B value=2 3
cpu,host=A value=2 11
cpu,host=A value=5 12
```

Example return value:

```
{
    "results": [
        {
            "name": "cpu",
            "tags": {
                "host": "A"
            },
            "columns": [
                "time",
                "mean"
            ],
            "values": [
                [
                    "0",
                    0
                ],
                [
                    "10",
                    2
                ],
                [
                    "20",
                    null
                ],
            ]
        },
        {
            "name": "cpu",
            "tags": {
                "host": "B"
            },
            "columns": [
                "time",
                "mean"
            ],
            "values": [
                [
                    "0",
                    2
                ],
                [
                    "10",
                    null
                ],
                [
                    "20",
                    null
                ],
            ]
        }
    ]
}
```

The current implementation of fill does this:

```
{
    "results": [
        {}
    ]
}
```

But, if you remove `host` from the group by and perform a select on an empty interval, you get something more similar to the proposed output above:

```
{
    "results": [
        {
            "name": "cpu",
            "columns": [
                "time",
                "mean"
            ],
            "values": [
                [
                    "0",
                    null
                ],
                [
                    "10",
                    null
                ],
                [
                    "20",
                    null
                ],
            ]
        }
    ]
}
```

**Comment by jsternberg** [comment]
@pauldix do you have any idea what we should be doing in regards to the problem detailed above?

**Comment by benbjohnson** [comment]
:+1:

**Comment by pauldix** [comment]
@jsternberg if there are no points in the entire query interval for the given tag set, it shouldn't be filled. Basically, only fill tag sets that actually have at least one point in the query interval.

**Comment by jsternberg** [comment]
@pauldix just to confirm, the integration test that fills in an interval with no points should be changed to return nothing, correct?

**Pull request merged**
